import fs from 'fs';
import crypto from 'crypto';
import { InstantRamanProtocol, IrpModelResult } from './src/engine/protocol';

function generateExampleIrp(): InstantRamanProtocol {
  const filePath = 'test_data.csv';
  const fileBuffer = fs.readFileSync(filePath);
  const fileHash = crypto.createHash('sha256').update(fileBuffer).digest('hex');
  
  // Generate the 15-entry matrix
  const perturbationSteps = [-10, -5, 0, 5, 10];
  const models: ("lorentzian" | "gaussian" | "voigt")[] = ["lorentzian", "gaussian", "voigt"];
  const all_model_results: IrpModelResult[] = [];

  for (const step of perturbationSteps) {
    for (const model of models) {
      // Simulate an ill-conditioned case occasionally, or just reliable for voigt
      const isIllConditioned = model === "lorentzian" && step === -10;
      
      all_model_results.push({
        model_type: model,
        boundary_perturbation_step: step,
        boundary_left: 1300.0 + (step * 0.5), // dummy math
        boundary_right: 1365.0 - (step * 0.5),
        fitted_center: isIllConditioned ? null : 1332.6 + (Math.random() - 0.5) * 0.2,
        fitted_fwhm: isIllConditioned ? null : 8.2 + (Math.random() - 0.5) * 0.1,
        fitted_amplitude: isIllConditioned ? null : 15000.5 + (Math.random() - 0.5) * 100,
        fitted_center_statistical_error: isIllConditioned ? null : 0.15 + Math.random() * 0.05,
        fitted_fwhm_statistical_error: isIllConditioned ? null : 0.10 + Math.random() * 0.05,
        fitted_amplitude_statistical_error: isIllConditioned ? null : 50.0 + Math.random() * 10,
        statistical_uncertainty_status: isIllConditioned ? "ill_conditioned" : "reliable",
        r_squared: isIllConditioned ? null : (model === "voigt" ? 0.998 : 0.95),
        reduced_chi_squared: isIllConditioned ? null : 1.2,
        convergence_status: isIllConditioned ? "failed" : "converged"
      });
    }
  }

  const irp: InstantRamanProtocol = {
    protocol_metadata: {
      instant_raman_version: "2.1.0",
      protocol_version: "1.0.0",
      protocol_id: crypto.randomUUID(),
      created_at: new Date().toISOString(),
      created_by: "Anonymous"
    },
    source_data_record: {
      original_filename: "test_data.csv",
      file_format_detected: "csv",
      wavenumber_range: { min: 200.5, max: 3500.2 },
      wavenumber_spacing: 1.5,
      number_of_data_points: 2200,
      file_hash: fileHash
    },
    processing_steps: [
      {
        step_number: 1,
        step_name: "cosmic_ray_rejection",
        applied: true,
        parameters: {
          algorithm: "MAD_zscore",
          threshold: 5.0,
          spikes_detected: 2,
          spikes_removed: 2,
          spike_positions: [1024.5, 2048.1]
        }
      },
      {
        step_number: 2,
        step_name: "baseline_correction",
        applied: true,
        parameters: {
          algorithm: "SNIP",
          iterations: 64,
          mode: "auto"
        }
      },
      {
        step_number: 3,
        step_name: "normalization",
        applied: false,
        parameters: {
          method: "none",
          reference_wavenumber: null
        }
      },
      {
        step_number: 4,
        step_name: "peak_detection",
        applied: true,
        parameters: {
          method: "parabolic_interpolation",
          minimum_height_threshold: 5.0,
          minimum_separation: 15.0,
          peaks_detected: 1,
          peak_positions: [1332.5]
        }
      }
    ],
    fitting_record: [
      {
        peak_id: 1,
        nominal_center: 1332.5,
        boundary_left: 1300.0,
        boundary_right: 1365.0,
        boundary_perturbation_range: 10.0,
        best_fit_model: "voigt",
        fitted_center: 1332.6,
        fitted_center_statistical_error: 0.15,
        fitted_fwhm: 8.2,
        fitted_amplitude: 15000.5,
        r_squared: 0.998,
        reduced_chi_squared: 1.2,
        epistemic_center_min: 1332.1,
        epistemic_center_max: 1333.0,
        epistemic_standard_deviation: 0.45,
        combined_uncertainty: 0.47,
        convergence_status: "converged",
        all_model_results: all_model_results
      }
    ],
    integration_record: [
      {
        peak_id: 1,
        boundary_left: 1300.0,
        boundary_right: 1365.0,
        local_baseline_left_intensity: 100.5,
        local_baseline_right_intensity: 105.2,
        integration_method: "simpsons",
        integrated_area: 125000.0,
        units: "counts * cm^-1"
      }
    ],
    reproducibility_guarantee: "This protocol was generated by Instant Raman. Applying this protocol to the source file identified by the SHA-256 hash recorded above will produce numerically identical results to within floating point precision."
  };

  return irp;
}

const example = generateExampleIrp();
fs.writeFileSync('example_protocol.irp', JSON.stringify(example, null, 2));
console.log("IRP file written to example_protocol.irp");
